[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"

[dev]
  command = "cd frontend && npm start"
  port = 3000
  publish = "frontend/build"

[[redirects]]
  from = "/api/*"
  to = "https://your-django-api.com/api/:splat"
  status = 200
  force = true